(cl:defpackage traj_gennav-srv
  (:use )
  (:export
   "EXECUTEPATH"
   "<EXECUTEPATH-REQUEST>"
   "EXECUTEPATH-REQUEST"
   "<EXECUTEPATH-RESPONSE>"
   "EXECUTEPATH-RESPONSE"
   "READPATHFROMFILE"
   "<READPATHFROMFILE-REQUEST>"
   "READPATHFROMFILE-REQUEST"
   "<READPATHFROMFILE-RESPONSE>"
   "READPATHFROMFILE-RESPONSE"
  ))

