// Generated by gencpp from file traj_gennav/ExecutePath.msg
// DO NOT EDIT!


#ifndef TRAJ_GENNAV_MESSAGE_EXECUTEPATH_H
#define TRAJ_GENNAV_MESSAGE_EXECUTEPATH_H

#include <ros/service_traits.h>


#include <traj_gennav/ExecutePathRequest.h>
#include <traj_gennav/ExecutePathResponse.h>


namespace traj_gennav
{

struct ExecutePath
{

typedef ExecutePathRequest Request;
typedef ExecutePathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecutePath
} // namespace traj_gennav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_gennav::ExecutePath > {
  static const char* value()
  {
    return "716e25f9d9dc76ceba197f93cbf05dc7";
  }

  static const char* value(const ::traj_gennav::ExecutePath&) { return value(); }
};

template<>
struct DataType< ::traj_gennav::ExecutePath > {
  static const char* value()
  {
    return "traj_gennav/ExecutePath";
  }

  static const char* value(const ::traj_gennav::ExecutePath&) { return value(); }
};


// service_traits::MD5Sum< ::traj_gennav::ExecutePathRequest> should match
// service_traits::MD5Sum< ::traj_gennav::ExecutePath >
template<>
struct MD5Sum< ::traj_gennav::ExecutePathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_gennav::ExecutePath >::value();
  }
  static const char* value(const ::traj_gennav::ExecutePathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_gennav::ExecutePathRequest> should match
// service_traits::DataType< ::traj_gennav::ExecutePath >
template<>
struct DataType< ::traj_gennav::ExecutePathRequest>
{
  static const char* value()
  {
    return DataType< ::traj_gennav::ExecutePath >::value();
  }
  static const char* value(const ::traj_gennav::ExecutePathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_gennav::ExecutePathResponse> should match
// service_traits::MD5Sum< ::traj_gennav::ExecutePath >
template<>
struct MD5Sum< ::traj_gennav::ExecutePathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_gennav::ExecutePath >::value();
  }
  static const char* value(const ::traj_gennav::ExecutePathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_gennav::ExecutePathResponse> should match
// service_traits::DataType< ::traj_gennav::ExecutePath >
template<>
struct DataType< ::traj_gennav::ExecutePathResponse>
{
  static const char* value()
  {
    return DataType< ::traj_gennav::ExecutePath >::value();
  }
  static const char* value(const ::traj_gennav::ExecutePathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_GENNAV_MESSAGE_EXECUTEPATH_H
