// Generated by gencpp from file traj_gennav/ReadPathFromFile.msg
// DO NOT EDIT!


#ifndef TRAJ_GENNAV_MESSAGE_READPATHFROMFILE_H
#define TRAJ_GENNAV_MESSAGE_READPATHFROMFILE_H

#include <ros/service_traits.h>


#include <traj_gennav/ReadPathFromFileRequest.h>
#include <traj_gennav/ReadPathFromFileResponse.h>


namespace traj_gennav
{

struct ReadPathFromFile
{

typedef ReadPathFromFileRequest Request;
typedef ReadPathFromFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadPathFromFile
} // namespace traj_gennav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traj_gennav::ReadPathFromFile > {
  static const char* value()
  {
    return "716e25f9d9dc76ceba197f93cbf05dc7";
  }

  static const char* value(const ::traj_gennav::ReadPathFromFile&) { return value(); }
};

template<>
struct DataType< ::traj_gennav::ReadPathFromFile > {
  static const char* value()
  {
    return "traj_gennav/ReadPathFromFile";
  }

  static const char* value(const ::traj_gennav::ReadPathFromFile&) { return value(); }
};


// service_traits::MD5Sum< ::traj_gennav::ReadPathFromFileRequest> should match
// service_traits::MD5Sum< ::traj_gennav::ReadPathFromFile >
template<>
struct MD5Sum< ::traj_gennav::ReadPathFromFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traj_gennav::ReadPathFromFile >::value();
  }
  static const char* value(const ::traj_gennav::ReadPathFromFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_gennav::ReadPathFromFileRequest> should match
// service_traits::DataType< ::traj_gennav::ReadPathFromFile >
template<>
struct DataType< ::traj_gennav::ReadPathFromFileRequest>
{
  static const char* value()
  {
    return DataType< ::traj_gennav::ReadPathFromFile >::value();
  }
  static const char* value(const ::traj_gennav::ReadPathFromFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traj_gennav::ReadPathFromFileResponse> should match
// service_traits::MD5Sum< ::traj_gennav::ReadPathFromFile >
template<>
struct MD5Sum< ::traj_gennav::ReadPathFromFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traj_gennav::ReadPathFromFile >::value();
  }
  static const char* value(const ::traj_gennav::ReadPathFromFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traj_gennav::ReadPathFromFileResponse> should match
// service_traits::DataType< ::traj_gennav::ReadPathFromFile >
template<>
struct DataType< ::traj_gennav::ReadPathFromFileResponse>
{
  static const char* value()
  {
    return DataType< ::traj_gennav::ReadPathFromFile >::value();
  }
  static const char* value(const ::traj_gennav::ReadPathFromFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJ_GENNAV_MESSAGE_READPATHFROMFILE_H
