// Generated by gencpp from file drone_school/CreatePPComTopicResponse.msg
// DO NOT EDIT!


#ifndef DRONE_SCHOOL_MESSAGE_CREATEPPCOMTOPICRESPONSE_H
#define DRONE_SCHOOL_MESSAGE_CREATEPPCOMTOPICRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_school
{
template <class ContainerAllocator>
struct CreatePPComTopicResponse_
{
  typedef CreatePPComTopicResponse_<ContainerAllocator> Type;

  CreatePPComTopicResponse_()
    : result()  {
    }
  CreatePPComTopicResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CreatePPComTopicResponse_

typedef ::drone_school::CreatePPComTopicResponse_<std::allocator<void> > CreatePPComTopicResponse;

typedef boost::shared_ptr< ::drone_school::CreatePPComTopicResponse > CreatePPComTopicResponsePtr;
typedef boost::shared_ptr< ::drone_school::CreatePPComTopicResponse const> CreatePPComTopicResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_school::CreatePPComTopicResponse_<ContainerAllocator1> & lhs, const ::drone_school::CreatePPComTopicResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_school::CreatePPComTopicResponse_<ContainerAllocator1> & lhs, const ::drone_school::CreatePPComTopicResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_school

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::drone_school::CreatePPComTopicResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_school/CreatePPComTopicResponse";
  }

  static const char* value(const ::drone_school::CreatePPComTopicResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result            # Return 'succeeded' for 'failed'\n"
;
  }

  static const char* value(const ::drone_school::CreatePPComTopicResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CreatePPComTopicResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_school::CreatePPComTopicResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_school::CreatePPComTopicResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_SCHOOL_MESSAGE_CREATEPPCOMTOPICRESPONSE_H
