// Generated by gencpp from file drone_school/CreatePPComTopic.msg
// DO NOT EDIT!


#ifndef DRONE_SCHOOL_MESSAGE_CREATEPPCOMTOPIC_H
#define DRONE_SCHOOL_MESSAGE_CREATEPPCOMTOPIC_H

#include <ros/service_traits.h>


#include <drone_school/CreatePPComTopicRequest.h>
#include <drone_school/CreatePPComTopicResponse.h>


namespace drone_school
{

struct CreatePPComTopic
{

typedef CreatePPComTopicRequest Request;
typedef CreatePPComTopicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CreatePPComTopic
} // namespace drone_school


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drone_school::CreatePPComTopic > {
  static const char* value()
  {
    return "04b00a4c4e03cffa324c24830dde7e4a";
  }

  static const char* value(const ::drone_school::CreatePPComTopic&) { return value(); }
};

template<>
struct DataType< ::drone_school::CreatePPComTopic > {
  static const char* value()
  {
    return "drone_school/CreatePPComTopic";
  }

  static const char* value(const ::drone_school::CreatePPComTopic&) { return value(); }
};


// service_traits::MD5Sum< ::drone_school::CreatePPComTopicRequest> should match
// service_traits::MD5Sum< ::drone_school::CreatePPComTopic >
template<>
struct MD5Sum< ::drone_school::CreatePPComTopicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drone_school::CreatePPComTopic >::value();
  }
  static const char* value(const ::drone_school::CreatePPComTopicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_school::CreatePPComTopicRequest> should match
// service_traits::DataType< ::drone_school::CreatePPComTopic >
template<>
struct DataType< ::drone_school::CreatePPComTopicRequest>
{
  static const char* value()
  {
    return DataType< ::drone_school::CreatePPComTopic >::value();
  }
  static const char* value(const ::drone_school::CreatePPComTopicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drone_school::CreatePPComTopicResponse> should match
// service_traits::MD5Sum< ::drone_school::CreatePPComTopic >
template<>
struct MD5Sum< ::drone_school::CreatePPComTopicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drone_school::CreatePPComTopic >::value();
  }
  static const char* value(const ::drone_school::CreatePPComTopicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_school::CreatePPComTopicResponse> should match
// service_traits::DataType< ::drone_school::CreatePPComTopic >
template<>
struct DataType< ::drone_school::CreatePPComTopicResponse>
{
  static const char* value()
  {
    return DataType< ::drone_school::CreatePPComTopic >::value();
  }
  static const char* value(const ::drone_school::CreatePPComTopicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONE_SCHOOL_MESSAGE_CREATEPPCOMTOPIC_H
